### ISSUE TITLE
modification of the board for commercial use

### ISSUE THREAD

**Issue by worldspawn00** [mohoyt/litl#1]
Hi, 

Couldn't figure out how to contact you, I'm wanting to sell a version of your litl board in my etsy shop, I made several major modifications to the design, and per your request, I'm asking permission to sell my version of the board! I've attached an image of the updates (added hotswap socket options, added 2nd OLED location, added switch option to 2nd encoder position, added reset button, added optional SMD diode pads, and cleaned up traces significantly).  I've left the design attribution to you on the PCB with a note that it's been modified by myself.  Let me know if I can put this version up on my shop.

Thanks!

Worldspawn00
(you can contact me directly on Discord at Worldspawn#0110)

![image](https://user-images.githubusercontent.com/3613128/189027732-2f33049a-118b-4e23-9ce6-e0af7c04d578.png)
![image](https://user-images.githubusercontent.com/3613128/189028076-359c970f-59a0-4ba5-bae8-b6b022c4e435.png)

**Comment by mohoyt** [comment]
Hey Worldspawn00!

Sorry for the delay in getting back to you! My GitHub notifications are off so I didn't notice this until today. I like the modifications and changes that you've made to the board! Would you consider sharing a small amount of proceeds from each sale of the board, and limiting your sales of the board to the Americas? If so, then I'd be happy for you to sell your version. 

Thanks again! 
mohoyt (also on Discord at mojibber#1632)

**Comment by EzioFenix** [comment]
I used your keyboard layout, but I have little doubts about, when you want to change from a large enter key to two keys, what do you change? Do you only put the switches according to your layout and what do you modify in the code?

I feel that the documentation lacks distribution, documentation and other inconveniences, I would like to work with you to improve it and make a distribution for the Spanish language devorak programmer, and publish it in your repository.

**Comment by worldspawn00** [comment]
> I used your keyboard layout, but I have little doubts about, when you want to change from a large enter key to two keys, what do you change? Do you only put the switches according to your layout and what do you modify in the code?

The extra key beside the enter is needed for some international (any layout that uses ISO enter) and non-standard layouts, it's part of the home row and gets a lot of use as a typing key, so it's nice to have an option to place an extra switch there between the L and Enter keys.

Code modification is simple, as the position already exists in the original matrix (even though it's not used/assigned), the only extra step is adding it into the layout.
